services:
  app:
    container_name: broker_app
    image: broker_app:app
    build:
      context: .
      args:
        RAILS_ENV: development
    env_file: .env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:password@postgres:5432/lti_broker}
      RAILS_ENV: development
    volumes:
      - .:/usr/src/app
      - bundle-volume:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - broker_redis
      - postgres

  postgres:
    image: postgres:14.6-alpine3.17
    restart: unless-stopped
    volumes:
      - ./data/postgres/14/database_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2-alpine3.17
    restart: unless-stopped
    volumes:
      - ./data/redis/database_data:/data

  prod:
    container_name: broker_app_prod
    image: broker_app_prod:prod
    build:
      context: .
      args:
        RAILS_ENV: production
    env_file:
      - ./.env
    environment:
      DISABLE_DATABASE_ENVIRONMENT_CHECK: 1
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:password@postgres:5432/lti_broker}
      RAILS_ENV: production
      REDIS_URL: redis://:BCsy8zMwZay669ii@broker_redis:6379/0
      MCONF_REDIS_HOST: broker_redis
      MCONF_REDIS_PASSWORD: BCsy8zMwZay669ii
      MCONF_REDIS_PORT: 6379
      MCONF_REDIS_DB: 0
      PROMETHEUS_EXPORTER_HOST: prod_exporter
      PROMETHEUS_EXPORTER_PORT: 9394
      PUMA_WORKERS: 1
      LOGRAGE_ENABLED: 1
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - broker_redis
      - prod_exporter

  prod_exporter:
    container_name: broker_prod_exporter
    image: broker_app_prod:prod
    tty: true
    stdin_open: true
    ports:
      - "9394:9394"
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
    command: bundle exec prometheus_exporter -b 0.0.0.0 -p 9394 --prefix 'broker_app_'

  broker_redis:
    container_name: broker_dev_redis
    image: redis:3.2
    expose:
      - "6379"
    command: redis-server --requirepass "BCsy8zMwZay669ii"

  broker_worker:
    container_name: broker_dev_resque_worker
    image: broker_app:app
    depends_on:
      - postgres
      - broker_redis
    env_file:
      - ./.env
    environment:
      - QUEUE=*
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:password@postgres:5432/lti_broker}
    volumes:
      - ./:/usr/src/app
      - bundle-volume:/usr/src/bundle
    command: "bin/rake resque:work"

  broker_scheduler:
    container_name: broker_dev_resque_scheduler
    image: broker_app:app
    depends_on:
      - postgres
      - broker_redis
    env_file:
      - ./.env
    volumes:
      - ./:/usr/src/app
      - bundle-volume:/usr/src/bundle
    command: "bin/rake resque:scheduler"

volumes:
  bundle-volume:
