version: '3'

services:
  app:
    build:
      context: .
      args:
        RAILS_ENV: development
    env_file: .env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:password@postgres:5432/lti_broker}
      RAILS_ENV: development
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    links:
      - postgres

  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
